[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
complexhook = "hoo9kSHtfFY6PLUoqEkHcZQJpTQvDYBi16GNXji8Z98"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/solana/hooks/keys/CptnNxRJp2adjccrLA3P1UvFVpPsZ3HRU9Uui7egGRDJ.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
